---

- name: Effort to maintain credential of BaaS worker servers
  hosts: dev_baas-workers_grp
  gather_facts: "no"
  vars_files:
    - "group_vars/prod-workers"
  # pre_tasks:
  #   - assert:
  #       that:
  #         - "usernames is defined"
  tasks:

    - name: read the baas_users file
      shell: "cat /root/baas/baas_users"
      register: ulist
      delegate_to: 127.0.0.1

    - debug:
        #msg: "display {{item}}"
        var: ulist

    # - local_action: lineinfile line="{{ item }}" dest="/root/baas/baas_users" backup=yes
    #   with_items: "{{ usernames.strip().replace(' ', '').replace(',', '\n').split('\n') }}"
